root: true
plugins:
  - '@typescript-eslint'
extends:
  - standard
  - 'plugin:@typescript-eslint/recommended'
  - standard-with-typescript
  - prettier
env:
  browser: true
  node: false
globals:
  __DEV__: readonly
  __PROD__: readonly
rules:
  camelcase: off
  'import/export': off
  lines-between-class-members: off
  no-dupe-class-members: off
  # using @typescript-eslint/no-useless-constructor instead
  no-useless-constructor: off
  spaced-comment:
    - error
    - always
    - markers: ['/']
      exceptions: ['/']
  '@typescript-eslint/adjacent-overload-signatures': error
  '@typescript-eslint/array-type': [error, { default: array-simple }]
  '@typescript-eslint/naming-convention':
    - error
    - selector: default
      format:
        - camelCase
      leadingUnderscore: allow
    - selector: typeLike
      format:
        - PascalCase
      leadingUnderscore: allow
    - selector: memberLike
      format:
        - camelCase
        - PascalCase
        - UPPER_CASE
      leadingUnderscore: allowSingleOrDouble
      trailingUnderscore: allowSingleOrDouble
    - selector: memberLike
      modifiers: ['requiresQuotes']
      format: null
    - selector: enumMember
      format:
        - PascalCase
        - UPPER_CASE
      leadingUnderscore: allowSingleOrDouble
      trailingUnderscore: allowSingleOrDouble
    - selector: variableLike
      format:
        - camelCase
        - UPPER_CASE
      leadingUnderscore: allowSingleOrDouble
      trailingUnderscore: allowSingleOrDouble
    - selector: variableLike
      format: null
      filter:
        regex: '^(?:child_process|ResEdit)$'
        match: true
    - selector: enumMember
      format: null
      filter:
        regex: '^(?:DOS_Windows16|DOS_Windows32|NT_Windows32)$'
        match: true
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': error
  '@typescript-eslint/lines-between-class-members': off
  '@typescript-eslint/member-ordering':
    - error
    - default:
        - public-static-field
        - private-static-field
        - public-instance-field
        - private-instance-field
        - public-constructor
        - private-constructor
  '@typescript-eslint/no-empty-function':
    - error
    - allow:
        - protected-constructors
        - private-constructors
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-useless-constructor': error
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/prefer-includes': off
overrides:
  - files: ['./*.js', 'examples/**/*.js', 'tools/**/*.js']
    env:
      browser: false
      node: true
    rules:
      '@typescript-eslint/no-var-requires': off
  - files: ['**/*.ts', '**/*.tsx']
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ./tsconfig.json
    rules:
      '@typescript-eslint/strict-boolean-expressions':
        - error
        - allowNullableBoolean: true
