name: Main CI
on:
  push:

env:
  NODE_VERSION: 14
  NPM_VERSION: 7

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Setup npm
        run: npm i -g npm@${{ env.NPM_VERSION }}
      - name: Cache node modules
        id: node_modules_cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: Install
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Type check
        run: npm run typecheck
      - name: Lint check
        run: npm run lint
      - name: Test
        run: npm run test
  windows-test:
    runs-on: windows-latest
    env:
      TEST_IGNORE_256_ICON: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Setup npm
        run: npm i -g npm@${{ env.NPM_VERSION }}
      - name: Cache node modules
        id: node_modules_cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: Install
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test (x86)
        run: npm run test:win-x86
      - name: Test (x64)
        run: npm run test:win-x64
