name: Main CI
on:
  push:

jobs:
  get-vars:
    uses: ./.github/workflows/nodevars.yml

  main:
    needs: get-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.get-vars.outputs.node-version }}
          cache: npm
      - name: Setup npm
        run: npm i -g npm@${{ needs.get-vars.outputs.npm-version }}
      - name: Cache node modules
        id: node_modules_cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: Install
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Type check
        run: npm run typecheck
      - name: Lint check
        run: npm run lint
      - name: Test
        run: npm run test
  windows-test:
    needs: get-vars
    runs-on: windows-latest
    env:
      TEST_IGNORE_256_ICON: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.get-vars.outputs.node-version }}
          cache: npm
      - name: Override npm prefix for using specific npm version
        shell: pwsh
        run: |
          $prefix = "$env:USERPROFILE\npm-prefix"
          npm config set prefix $prefix
          "$prefix\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Setup npm
        run: npm i -g npm@${{ needs.get-vars.outputs.npm-version }}
      - name: Cache node modules
        id: node_modules_cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: Install
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test (x86)
        run: npm run test:win-x86
      - name: Test (x64)
        run: npm run test:win-x64
