name: Main CI
on:
  push:

jobs:
  get-vars:
    uses: ./.github/workflows/nodevars.yml

  main:
    needs: get-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ needs.get-vars.outputs.node-version }}
          cache: npm
      - name: Setup npm
        run: npm i -g npm@${{ needs.get-vars.outputs.npm-version }}
      - name: Cache node modules
        id: node_modules_cache
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: Install
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Type check
        run: npm run typecheck
      - name: Lint check
        run: npm run lint
      - name: Test
        run: npm run test
  windows-test:
    needs: get-vars
    runs-on: windows-latest
    env:
      TEST_IGNORE_256_ICON: 1
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ needs.get-vars.outputs.node-version }}
          cache: npm
      - name: Cache node modules
        id: node_modules_cache
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: Install
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        # use npx instead of installing npm globally to avoid permission error
        run: npx -y npm@${{ needs.get-vars.outputs.npm-version }} ci
      - name: Test (x86)
        # use normal npm (which should not affect to the test)
        run: npm run test:win-x86
      - name: Test (x64)
        run: npm run test:win-x64
